# Generated by Django 3.1.7 on 2021-03-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0003_auto_20210312_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_time', models.CharField(blank=True, max_length=14, null=True)),
                ('transaction_amount', models.CharField(blank=True, max_length=12, null=True)),
                ('business_shortcode', models.CharField(blank=True, max_length=6, null=True)),
                ('bill_ref_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('org_account_balance', models.CharField(blank=True, max_length=12, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=20, null=True)),
                ('MSISDN', models.CharField(blank=True, max_length=12, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
