# Generated by Django 3.1.7 on 2021-03-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0004_c2bpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='bill_ref_number',
            new_name='BillRefNumber',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='business_shortcode',
            new_name='BusinessShortCode',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='invoice_number',
            new_name='InvoiceNumber',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='middle_name',
            new_name='MiddleName',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='org_account_balance',
            new_name='OrgAccountBalance',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='third_party_trans_id',
            new_name='ThirdPartyTransID',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='transaction_amount',
            new_name='TransAmount',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='transaction_id',
            new_name='TransID',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='transaction_time',
            new_name='TransTime',
        ),
        migrations.RenameField(
            model_name='c2bpayment',
            old_name='transaction_type',
            new_name='TransactionType',
        ),
    ]
