# Generated by Django 3.1.7 on 2021-03-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0005_auto_20210324_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaCallBacks',
        ),
        migrations.DeleteModel(
            name='MpesaCalls',
        ),
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
    ]
